[build]
command = "pip install -r requirements.txt"
functions = "api"
publish = "."

[build.environment]
PYTHON_VERSION = "3.9"

[[redirects]]
from = "/*"
to = "/.netlify/functions/handler"
status = 200
force = false
